name: "Get version"
description: "Get tag and mnemo version from pyproject.toml"

outputs:
  title:
    description: "Title to be displayed for release"
    value: ${{ steps.get_meta.outputs.TITLE }}
  tag:
    description: "Python's version management-friendly tag"
    value: ${{ steps.get_meta.outputs.TAG }}

runs:
  using: "composite"
  steps:
    - id: get_meta
      shell: bash
      run: |
        echo "TITLE=$( echo '${{ github.event.pull_request.title }}' | sed -r 's/^rc-(.+)$/ \1/' )" >> $GITHUB_OUTPUT
        echo "TAG=$( poetry version -s )" >> $GITHUB_OUTPUT

