name: Poetry build & publish release

on:
  pull_request:
    branches:
      - master
    types: closed

jobs:
  build:
    if: |
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.title, 'rc-')
    outputs:
      tag: ${{ steps.get_meta.outputs.tag }}
      title: ${{ steps.get_meta.outputs.title }}

    name: Poetry build .whl artifacts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup_environment
      with:
        python-version: ${{ vars.PYTHON }}
    - name: Install deps & build
      run: |
        poetry install --no-interaction
        poetry build -f wheel -vv
    - uses: actions/upload-artifact@v4
      with:
        name: wheel
        path: dist/*.whl
    - id: get_meta
      uses: ./.github/actions/get_version

  artifacts:
    needs: build

    name: Publish artifacts on releases
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: wheel

    - name: Set tag and publish release
      run: |
        gh release create \
          ${{ needs.build.outputs.tag }} *whl \
          --title="${{ needs.build.outputs.title }}" \
          --repo="$GITHUB_REPOSITORY" \
          --generate-notes \

