name: Poetry build & publish release

on:
  pull_request:
    branches:
      - master
    types: closed

jobs:
  build:
    if: |
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.title, 'rc-')

    name: Poetry build .whl artifacts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup_environment
    - name: Install deps & build
      run: |
        poetry install --no-interaction
        poetry build -f wheel -vv
    - uses: actions/upload-artifact@v4
      with:
        name: wheel
        path: dist/*.whl

  artifacts:
    needs: build

    name: Publish artifacts on releases
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: wheel

    - id: get_meta
      uses: ./.github/actions/set_version
    - name: Set tag and publish release
      run: |
        gh release create \
          ${{ steps.get_meta.outputs.TAG }} *whl \
          --title="${{ steps.get_meta.outputs.TITLE }}" \
          --repo="$GITHUB_REPOSITORY" \
          --generate-notes \

