name: Run pre-merge checks

on:
  pull_request:
    branches:
      - master
    types: [synchronize, opened]
  push:
    branches:
      - master

jobs:
  checks_prepare:
    name: Collect changes
    runs-on: ubuntu-latest
    outputs:
      gh_actions: ${{ steps.changes.outputs.gh_actions }}
      python: ${{ steps.changes.outputs.python }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          python:
            - '**/*.py'
            - 'pyproject.toml'
          gh_actions:
            - '.github/workflows/**'
            - '.github/actions/**'

  run_gh:
    needs: checks_prepare
    if: needs.checks_prepare.outputs.gh_actions == 'true'
    uses: ./.github/workflows/gh_actions_checks.yml

  run_py:
    needs: checks_prepare
    if: needs.checks_prepare.outputs.python == 'true'
    uses: ./.github/workflows/python_checks.yml

