name: Run pre-merge checks

on:
  pull_request:
    branches:
      - master
    types: [synchronize, opened]
  push:
    branches:
      - master

jobs:
  checks_runner:
    name: Collect changes
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          python:
            - '**/*.py'
            - 'pyproject.toml'
          gh_actions:
            - '.github/workflows/**'
            - '.github/actions/**'
    - if: steps.changes.outputs.gh_actions == 'true'
      uses: ./.github/worksflows/gh_actions_checks.yml
    - if: steps.changes.outputs.python == 'true'
      uses: ./.github/worksflows/python_checks.yml

